name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *' # run every day at 5 am
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |-
        python latest_posts.py
        cat README.md
    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: 'Github Bot'
        author_email: 'me+githubbot@estebantorr.es'
        message: "Updated blogposts"
        pull: '--rebase --autostash ...'
